locales: zh_CN # 语言
log_level: INFO # 日志等级
check_update: true # 检测更新
agreed_to_disclaimer: false

after_finish: None # 任务完成后: "None"（无）"Exit"（退出）"Loop"（循环）"Shutdown"（关机）"Hibernate"（休眠）"Sleep"（睡眠）
power_limit: 160 # 循环运行所需开拓力
play_audio: false # 任务完成后播放提示音
use_windows_terminal: false # 使用 Windows 终端

ocr_path: .\3rdparty\PaddleOCR-json_v.1.3.0\PaddleOCR-json.exe
# 示例 C:\Users\i\AppData\Local\Programs\Python\Python311\python.exe
python_exe_path: ''

game_title_name: 崩坏：星穹铁道 # 窗口标题
game_process_name: StarRail # 进程名
game_path: C:\Program Files\Star Rail\Game\StarRail.exe # 游戏路径

power_total: 999 # 开拓力最大值
dispatch_count: 4 # 派遣次数

instance_type: 拟造花萼（金） # 副本类型: 侵蚀隧洞、凝滞虚影、拟造花萼（金）、拟造花萼（赤）
instance_names: # 副本名称
  拟造花萼（金）: 回忆之蕾
  拟造花萼（赤）: 毁灭之蕾
  凝滞虚影: 无
  侵蚀隧洞: 睿治之径
  历战余响: 毁灭的开端
power_needs: # 副本所需开拓力
  拟造花萼（金）: 60
  拟造花萼（赤）: 60
  凝滞虚影: 30
  侵蚀隧洞: 40
  历战余响: 30
borrow_character_enable: false # 强制使用支援角色
borrow_character_from: # 使用指定好友的支援角色
- 好友1
- 好友2
- 好友3
borrow_character: # 支援角色优先级
- Seele
- Blade
- JingYuan
- Kafka
- Clara
- Welt
- Yanqing
- Himeko
- Luocha
- Gepard
- Bailu
instance_team_enable: false # 打副本时自动切换队伍
instance_team_number: '1' # 队伍编号
echo_of_war_enable: false # 体力优先完成3次「历战余响」
echo_of_war_timestamp: 0 # 上次完成3次「历战余响」的时间戳（每周运行）

dispatch_enable: true # 领取派遣奖励
mail_enable: true # 领取邮件奖励
assist_enable: true # 领取支援奖励
srpass_enable: false # 领取无名勋礼奖励

daily_forgottenhall_enable: false # 完成1次「忘却之庭」每日实训
daily_tasks: {} # 每日实训
last_run_timestamp: 0 # 上次运行日常的时间戳

fight_enable: false # 启用锄大地
fight_path: .\3rdparty\StarRailAssistant # 锄大地路径
fight_timeout: 6 # 锄大地超时（单位小时）
fight_team_enable: false # 锄大地时自动切换队伍
fight_team_number: '2' # 队伍编号
fight_requirements: false # 是否安装过依赖（更新后会重置为false）
fight_timestamp: 0 # 上次运行锄大地的时间戳（每天运行）

universe_enable: false # 启用模拟宇宙
universe_bonus_enable: false # 领取沉浸奖励
universe_path: .\3rdparty\Auto_Simulated_Universe # 模拟宇宙路径
universe_timeout: 20 # 模拟宇宙超时（单位小时）
universe_requirements: false # 是否安装过依赖（更新后会重置为false）
universe_timestamp: 0 # 上次运行模拟宇宙的时间戳（每周运行）

forgottenhall_enable: false # 启用忘却之庭
forgottenhall_level: # 混沌回忆关卡范围
- 1
- 10
forgottenhall_retries: 1 # 混沌回忆挑战失败后的重试次数
# 混沌回忆队伍
# 数字代表秘技使用次数，其中 -1 代表最后一个放秘技和普攻的角色
# 角色对应的英文名字可以在 "March7thAssistant\assets\images\character" 中查看
forgottenhall_team1: # 队伍1
- -
    Asta
  - -1
- - Natasha
  - 0
- - Tingyun
  - 2
- - JingYuan
  - 1
forgottenhall_team2: # 队伍2
- -
    Bronya
  - 1
- - Luocha
  - 1
- - SilverWolf
  - -1
- - Qingque
  - 1
forgottenhall_timestamp: 0 # 上次运行混沌回忆的时间戳（每周运行，如已经满星则跳过）

hotkey_technique: e # 游戏内设置的秘技按键

# 可选消息通知 Telegram已适配支持发送截图
# 还支持更多推送查看下面的链接仿照格式配置即可
# https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Onepush-configuration-[CN]
notify_winotify_enable: true # 启用Windows原生通知

notify_telegram_enable: false # 启用Telegram通知
notify_telegram_token: ''
notify_telegram_userid: ''
notify_telegram_api_url: ''

notify_wechatworkapp_enable: false # 启用企业微信应用通知
notify_wechatworkapp_corpid: ''
notify_wechatworkapp_corpsecret: ''
notify_wechatworkapp_agentid: ''
